- name: Query Hosts
  hosts: all
  gather_facts: no
  vars:
    ansible_user: "{{ duser }}"
    ansible_password: "{{ dpwd }}"
    ansible_ssh_retries: 10
    ansible_host_key_checking: False
  vars_files: #insert your encrypted password file here if not using certificate based auth
  roles:
    - roles/RedfishStatus